# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dcdio', [dirname(__file__)])
        except ImportError:
            import _dcdio
            return _dcdio
        if fp is not None:
            try:
                _mod = imp.load_module('_dcdio', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _dcdio = swig_import_helper()
    del swig_import_helper
else:
    import _dcdio
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def open_dcd_write(*args):
  return _dcdio.open_dcd_write(*args)
open_dcd_write = _dcdio.open_dcd_write

def write_dcdheader(*args):
  return _dcdio.write_dcdheader(*args)
write_dcdheader = _dcdio.write_dcdheader

def close_dcd_write(*args):
  return _dcdio.close_dcd_write(*args)
close_dcd_write = _dcdio.close_dcd_write

def open_dcd_read(*args):
  return _dcdio.open_dcd_read(*args)
open_dcd_read = _dcdio.open_dcd_read

def close_dcd_read(*args):
  return _dcdio.close_dcd_read(*args)
close_dcd_read = _dcdio.close_dcd_read

def read_dcdheader(*args):
  return _dcdio.read_dcdheader(*args)
read_dcdheader = _dcdio.read_dcdheader


def write_dcdstep(*args):
  return _dcdio.write_dcdstep(*args)
write_dcdstep = _dcdio.write_dcdstep

def read_dcdstep(*args):
  return _dcdio.read_dcdstep(*args)
read_dcdstep = _dcdio.read_dcdstep

